### PR TITLE
Spelling and grammar fixes in comments.

### PR DESCRIPTION
**Pull request by Tumbler**

### CODE REVIEW

**Comment by Kasijjuf** [comment]
While I will concede that the words are misspelled, you'll have to convince me about the comma.

**Comment by Tumbler** [comment]
> This condition can only be achieved using negative numbers or zero, or by using a combination of positive numbers that would fail one of the other tests.


The first "or" is joining a two item list. No comma is needed here. The second "or" is joining two independent clauses. Two independent clauses should be combined by a conjunction and a comma. [Here's a link to a poorly formatted website which must mean it's correct. :P](http://grammar.ccc.commnet.edu/grammar/commas.htm)

**Comment by Kasijjuf** [comment]
Those aren't two independent clauses; those are two adverbial phrases.

**Comment by Tumbler** [comment]
If that's the case then it really just needs to be a three item list:

>This condition can only be achieved using negative numbers, zero, or a combination of positive numbers that would fail one of the other tests.

**Comment by Kasijjuf** [comment]
How then do you propose to apply the parenthetical modifier to the first two list items in that sentence construct?

**Comment by Tumbler** [comment]
I see what you mean. I will concede on the grounds of readability versus total grammatical correctness.

**Comment by Tumbler** [comment]
Updated

**Pull request merged**
